export const strings = {
  linkAccountHeading: 'Access your notes anywhere',
  linkAccountSubheading: 'Create an account to sync across devices',
  labelChooseContact: 'How would you like to sign in?',
  labelEmail: 'Email',
  labelMobile: 'Mobile',
  labelPassword: 'Create a password',
  hintEmail: 'Email (optional)',
  hintMobile: 'Mobile number (optional)',
  hintPassword: 'Password (optional)',
  hintEmailRequired: 'Enter your email address',
  hintMobileRequired: 'Enter your mobile number',
  hintPasswordRequired: 'Create a password (min 6 characters)',
  btnSave: 'Save',
  btnCreateAccount: 'Create Account',
  btnMaybeLater: 'Maybe Later',
  btnUpdatePassword: 'Update Password',
  hintCurrentPassword: 'Current password',
  hintNewPassword: 'New password',
  hintConfirmPassword: 'Confirm new password',
  bannerVerifyEmail: 'Please verify your email.',
  bannerResend: 'Resend?',
  snackbarPasswordUpdated: 'Password updated successfully',
  snackbarWrongPassword: 'Current password is incorrect',
  snackbarGenericError: 'Something went wrong. Please try again.',
  errorFillOneField: 'Please fill in at least one field',
  errorFieldRequired: 'This field is required',
  errorPasswordsNoMatch: 'Passwords do not match',
  errorEmailRequired: 'Email address is required',
  errorMobileRequired: 'Mobile number is required',
  errorPasswordRequired: 'Password is required',
  errorPasswordTooShort: 'Password must be at least 6 characters',
  errorInvalidEmail: 'Please enter a valid email address',
  errorInvalidMobile: 'Please enter a valid mobile number',
};
