export const strings = {
  linkAccountHeading: 'Access your notes anywhere',
  hintEmail: 'Email (optional)',
  hintMobile: 'Mobile number (optional)',
  hintPassword: 'Password (optional)',
  btnSave: 'Save',
  btnMaybeLater: 'Maybe Later',
  btnUpdatePassword: 'Update Password',
  hintCurrentPassword: 'Current password',
  hintNewPassword: 'New password',
  hintConfirmPassword: 'Confirm new password',
  bannerVerifyEmail: 'Please verify your email.',
  bannerResend: 'Resend?',
  snackbarPasswordUpdated: 'Password updated successfully',
  snackbarWrongPassword: 'Current password is incorrect',
  snackbarGenericError: 'Something went wrong. Please try again.',
  errorFillOneField: 'Please fill in at least one field',
  errorFieldRequired: 'This field is required',
  errorPasswordsNoMatch: 'Passwords do not match',
};
