// Bundled verse list - World English Bible (WEB), public domain, no licensing/attribution
// requirements. getVerseForDate() below rotates through this array by day-of-year, so the exact
// count isn't load-bearing (any length works via modulo); this list favors well-known,
// comforting/encouraging verses spread across Psalms, Proverbs, the Gospels, and the Epistles.
export const VERSES: { text: string; reference: string }[] = [
  { text: "Be strong and courageous. Don't be afraid or scared of them, for Yahweh your God himself is who goes with you. He will not fail you nor forsake you.", reference: 'Deuteronomy 31:6' },
  { text: "Haven't I commanded you? Be strong and courageous. Don't be afraid. Don't be dismayed, for Yahweh your God is with you wherever you go.", reference: 'Joshua 1:9' },
  { text: "Go your way. Eat the fat, drink the sweet, and send portions to him for whom nothing is prepared, for today is holy to our Lord. Don't be grieved, for the joy of Yahweh is your strength.", reference: 'Nehemiah 8:10' },
  { text: 'Yahweh is my light and my salvation. Whom shall I fear? Yahweh is the strength of my life.', reference: 'Psalm 27:1' },
  { text: 'Yahweh is my shepherd; I shall lack nothing. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul. He guides me in the paths of righteousness for his name\'s sake.', reference: 'Psalm 23:1-3' },
  { text: 'For his anger is but for a moment. His favor is for a lifetime. Weeping may stay for the night, but joy comes in the morning.', reference: 'Psalm 30:5' },
  { text: 'Also delight yourself in Yahweh, and he will give you the desires of your heart.', reference: 'Psalm 37:4' },
  { text: 'Cast your burden on Yahweh and he will sustain you. He will never allow the righteous to be moved.', reference: 'Psalm 55:22' },
  { text: 'My soul rests in God alone. My salvation is from him. He alone is my rock, my salvation, and my fortress. I will never be greatly shaken.', reference: 'Psalm 62:1-2' },
  { text: 'My flesh and my heart fails, but God is the strength of my heart and my portion forever.', reference: 'Psalm 73:26' },
  { text: 'For Yahweh God is a sun and a shield. Yahweh will give grace and glory. He withholds no good thing from those who walk blamelessly.', reference: 'Psalm 84:11' },
  { text: 'Shout for joy to Yahweh, all you lands! Serve Yahweh with gladness. Come before his presence with singing. Know that Yahweh, he is God.', reference: 'Psalm 100:1-3' },
  { text: 'Your word is a lamp to my feet, and a light for my path.', reference: 'Psalm 119:105' },
  { text: 'Yahweh will fulfill that which concerns me. Your loving kindness, Yahweh, endures forever.', reference: 'Psalm 138:8' },
  { text: 'Yahweh is near to all those who call on him, to all who call on him in truth.', reference: 'Psalm 145:18' },
  { text: 'I will lift up my eyes to the hills. Where does my help come from? My help comes from Yahweh, who made heaven and earth.', reference: 'Psalm 121:1-2' },
  { text: 'Yahweh is near to those who have a broken heart, and saves those who have a crushed spirit.', reference: 'Psalm 34:18' },
  { text: 'God is our refuge and strength, a very present help in trouble.', reference: 'Psalm 46:1' },
  { text: 'This is the day that Yahweh has made. We will rejoice and be glad in it!', reference: 'Psalm 118:24' },
  { text: 'He who dwells in the secret place of the Most High will rest in the shadow of the Almighty. I will say of Yahweh, "He is my refuge and my fortress; my God, in whom I trust."', reference: 'Psalm 91:1-2' },
  { text: 'Cause me to hear your loving kindness in the morning, for I trust in you. Cause me to know the way in which I should walk, for I lift up my soul to you.', reference: 'Psalm 143:8' },
  { text: 'You will show me the path of life. In your presence is fullness of joy. In your right hand there are pleasures forever more.', reference: 'Psalm 16:11' },
  { text: 'Commit your deeds to Yahweh, and your plans shall succeed.', reference: 'Proverbs 16:3' },
  { text: 'A cheerful heart makes good medicine, but a crushed spirit dries up the bones.', reference: 'Proverbs 17:22' },
  { text: "Yahweh's name is a strong tower: the righteous run to him, and are safe.", reference: 'Proverbs 18:10' },
  { text: "Trust in Yahweh with all your heart, and don't lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.", reference: 'Proverbs 3:5-6' },
  { text: 'Strength and dignity are her clothing. She laughs at the time to come.', reference: 'Proverbs 31:25' },
  { text: 'You will keep whoever\'s mind is steadfast in perfect peace, because he trusts in you.', reference: 'Isaiah 26:3' },
  { text: 'but those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.', reference: 'Isaiah 40:31' },
  { text: "Don't you be afraid, for I am with you. Don't be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.", reference: 'Isaiah 41:10' },
  { text: 'When you pass through the waters, I will be with you, and through the rivers, they will not overflow you. When you walk through the fire, you will not be burned, and flame will not scorch you.', reference: 'Isaiah 43:2' },
  { text: 'For I know the thoughts that I think toward you, says Yahweh, thoughts of peace, and not of evil, to give you hope and a future.', reference: 'Jeremiah 29:11' },
  { text: "It is because of Yahweh's loving kindnesses that we are not consumed, because his mercies don't fail. They are new every morning. Great is your faithfulness.", reference: 'Lamentations 3:22-23' },
  { text: 'He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?', reference: 'Micah 6:8' },
  { text: 'Yahweh, your God, is among you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with singing.', reference: 'Zephaniah 3:17' },
  { text: "But seek first God's Kingdom and his righteousness; and all these things will be given to you as well.", reference: 'Matthew 6:33' },
  { text: "Therefore don't be anxious for tomorrow, for tomorrow will be anxious for itself. Each day's own evil is sufficient.", reference: 'Matthew 6:34' },
  { text: 'Come to me, all you who labor and are heavily burdened, and I will give you rest. Take my yoke upon you and learn from me, for I am gentle and humble in heart; and you will find rest for your souls. For my yoke is easy, and my burden is light.', reference: 'Matthew 11:28-30' },
  { text: 'Therefore I tell you, all things whatever you pray and ask for, believe that you have received them, and you shall have them.', reference: 'Mark 11:24' },
  { text: 'For nothing spoken by God is impossible.', reference: 'Luke 1:37' },
  { text: 'Again, therefore, Jesus spoke to them, saying, "I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life."', reference: 'John 8:12' },
  { text: 'I am the vine. You are the branches. He who remains in me and I in him bears much fruit, for apart from me you can do nothing.', reference: 'John 15:5' },
  { text: "Peace I leave with you. My peace I give to you; not as the world gives, I give to you. Don't let your heart be troubled, neither let it be fearful.", reference: 'John 14:27' },
  { text: 'I have told you these things, that in me you may have peace. In the world you have trouble; but cheer up! I have overcome the world.', reference: 'John 16:33' },
  { text: 'For God so loved the world, that he gave his only born Son, that whoever believes in him should not perish, but have eternal life.', reference: 'John 3:16' },
  { text: 'We know that all things work together for good for those who love God, for those who are called according to his purpose.', reference: 'Romans 8:28' },
  { text: "For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor any other created thing will be able to separate us from God's love which is in Christ Jesus our Lord.", reference: 'Romans 8:38-39' },
  { text: "Don't be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.", reference: 'Romans 12:2' },
  { text: 'Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope in the power of the Holy Spirit.', reference: 'Romans 15:13' },
  { text: "Love is patient and is kind. Love doesn't envy. Love doesn't brag, is not proud, doesn't behave itself inappropriately, doesn't seek its own way, is not provoked, takes no account of evil; doesn't rejoice in unrighteousness, but rejoices with the truth; bears all things, believes all things, hopes all things, and endures all things.", reference: '1 Corinthians 13:4-7' },
  { text: 'Let all that you do be done in love.', reference: '1 Corinthians 16:14' },
  { text: 'for we walk by faith, not by sight.', reference: '2 Corinthians 5:7' },
  { text: 'My grace is sufficient for you, for my power is made perfect in weakness.', reference: '2 Corinthians 12:9' },
  { text: 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law.', reference: 'Galatians 5:22-23' },
  { text: 'For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, that no one would boast.', reference: 'Ephesians 2:8-9' },
  { text: 'Now to him who is able to do exceedingly abundantly above all that we ask or think, according to the power that works in us, to him be the glory in the assembly and in Christ Jesus to all generations, forever and ever. Amen.', reference: 'Ephesians 3:20-21' },
  { text: 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.', reference: 'Philippians 4:6-7' },
  { text: 'I can do all things through Christ who strengthens me.', reference: 'Philippians 4:13' },
  { text: 'My God will supply every need of yours according to his riches in glory in Christ Jesus.', reference: 'Philippians 4:19' },
  { text: 'And whatever you do, work heartily, as for the Lord and not for men, knowing that from the Lord you will receive the reward of the inheritance; for you serve the Lord Christ.', reference: 'Colossians 3:23-24' },
  { text: 'Always rejoice. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus toward you.', reference: '1 Thessalonians 5:16-18' },
  { text: "For God didn't give us a spirit of fear, but of power, love, and self-control.", reference: '2 Timothy 1:7' },
  { text: 'Now faith is assurance of things hoped for, proof of things not seen.', reference: 'Hebrews 11:1' },
  { text: 'Be free from the love of money, content with such things as you have, for he has said, "I will in no way leave you, neither will I in any way forsake you."', reference: 'Hebrews 13:5' },
  { text: 'Count it all joy, my brothers, when you fall into various temptations, knowing that the testing of your faith produces endurance. Let endurance have its perfect work, that you may be perfect and complete, lacking in nothing.', reference: 'James 1:2-4' },
  { text: 'casting all your worries on him, because he cares for you.', reference: '1 Peter 5:7' },
  { text: 'There is no fear in love; but perfect love casts out fear, because fear has punishment. He who fears is not made perfect in love. We love him, because he first loved us.', reference: '1 John 4:18-19' },
  { text: 'He will wipe away every tear from their eyes. Death will be no more; neither will there be mourning, nor crying, nor pain any more. The first things have passed away.', reference: 'Revelation 21:4' },
];

export function getVerseForDate(date: Date): { text: string; reference: string } {
  const startOfYear = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - startOfYear.getTime();
  const dayOfYear = Math.floor(diff / 86400000);
  return VERSES[dayOfYear % VERSES.length];
}
