import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, Modal, Pressable, Platform, StatusBar } from 'react-native';
import { useRouter, type Href } from 'expo-router';
import { MaterialIcons } from '@expo/vector-icons';
import { User } from '../types/auth.types';
import { useAuth } from '../context/AuthContext';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

const C = {
  primary: '#0A5443',
  primaryFg: '#FFFFFF',
  success: '#4CAF50',
  successFg: '#FFFFFF',
  text: '#121212',
  textSec: '#37474F',
  borderSub: '#78909C',
  surface: '#FFFFFF',
  bg: '#FDFBF7',
};

interface UserAvatarProps {
  size?: number;
}

export function UserAvatar({ size = 40 }: UserAvatarProps) {
  const router = useRouter();
  const { user, logout } = useAuth();
  const [menuVisible, setMenuVisible] = useState(false);
  const insets = useSafeAreaInsets();

  if (!user) return null;

  // The Daily Brew entry only shows once the flag (resolved server-side, see
  // backend/featureflags.py) comes back on - avoids a dead-end menu item pointing at a hidden feature.
  const dailyBrewEnabled = user.daily_brew_enabled === true;

  const firstLetter = user.email.charAt(0).toUpperCase();

  const handleChangePassword = () => {
    setMenuVisible(false);
    router.push('/change-password');
  };

  const handleSettings = () => {
    setMenuVisible(false);
    router.push('/settings');
  };

  const handleCalendarSync = () => {
    setMenuVisible(false);
    // Not yet in the typed-routes cache (regenerated by the dev server / expo export), same as
    // the analytics-consent route elsewhere in this app.
    router.push('/calendar-sync-settings' as Href);
  };

  const handleDailyBrewSettings = () => {
    setMenuVisible(false);
    router.push('/news-source-settings' as Href);
  };

  const handleLogout = async () => {
    setMenuVisible(false);
    await logout();
    router.replace('/welcome');
  };

  // Calculate top position based on safe area + header height + extra margin
  const topOffset = insets.top + 65; // Safe area + header height + extra margin

  return (
    <>
      <TouchableOpacity
        onPress={() => setMenuVisible(true)}
        style={[
          styles.avatar,
          {
            width: size,
            height: size,
            borderRadius: size / 2,
          },
        ]}
      >
        <Text style={[styles.letter, { fontSize: size * 0.5 }]}>{firstLetter}</Text>
      </TouchableOpacity>

      <Modal
        visible={menuVisible}
        transparent
        animationType="fade"
        onRequestClose={() => setMenuVisible(false)}
      >
        <Pressable 
          style={[styles.modalOverlay, { paddingTop: topOffset }]} 
          onPress={() => setMenuVisible(false)}
        >
          <View style={styles.menuContainer}>
            <View style={styles.menuHeader}>
              <View style={styles.menuAvatar}>
                <Text style={styles.menuAvatarText}>{firstLetter}</Text>
              </View>
              <View style={styles.menuUserInfo}>
                <Text style={styles.menuUserName}>{user.name}</Text>
              </View>
            </View>
            
            <View style={styles.menuDivider} />
            
            <TouchableOpacity style={styles.menuItem} onPress={handleSettings}>
              <MaterialIcons name="privacy-tip" size={24} color={C.text} />
              <Text style={styles.menuText}>Data & Privacy</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.menuItem} onPress={handleCalendarSync}>
              <MaterialIcons name="sync" size={24} color={C.text} />
              <Text style={styles.menuText}>Calendar</Text>
            </TouchableOpacity>

            {dailyBrewEnabled && (
              <TouchableOpacity style={styles.menuItem} onPress={handleDailyBrewSettings}>
                <MaterialIcons name="wb-sunny" size={24} color={C.text} />
                {/* Named for the feature, not just its news row: the destination screen now owns
                    the verse and the daily quote as well, and a menu item promising only "News
                    from home" is how the quote toggle went missing from settings in the first
                    place. */}
                <Text style={styles.menuText}>Daily Brew</Text>
              </TouchableOpacity>
            )}

            <TouchableOpacity style={styles.menuItem} onPress={handleChangePassword}>
              <MaterialIcons name="lock" size={24} color={C.text} />
              <Text style={styles.menuText}>Change password</Text>
            </TouchableOpacity>

            <TouchableOpacity style={styles.menuItem} onPress={handleLogout}>
              <MaterialIcons name="logout" size={24} color={C.primary} />
              <Text style={[styles.menuText, { color: C.primary }]}>Log out</Text>
            </TouchableOpacity>
          </View>
        </Pressable>
      </Modal>
    </>
  );
}

const styles = StyleSheet.create({
  avatar: {
    backgroundColor: C.success,
    justifyContent: 'center',
    alignItems: 'center',
  },
  letter: {
    color: C.successFg,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    paddingRight: 21,
  },
  menuContainer: {
    backgroundColor: C.surface,
    borderRadius: 16,
    paddingVertical: 16,
    minWidth: 260,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  menuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  menuAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: C.success,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuAvatarText: {
    color: C.successFg,
    fontSize: 22,
    fontWeight: '700',
  },
  menuUserInfo: {
    marginLeft: 12,
    flex: 1,
  },
  menuUserName: {
    fontSize: 18,
    fontWeight: '600',
    color: C.text,
  },
  menuDivider: {
    height: 1,
    backgroundColor: C.borderSub + '30',
    marginVertical: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  menuText: {
    fontSize: 17,
    fontWeight: '500',
    color: C.text,
  },
});
